name: test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: buckaroobanzay/mtt@main
      with:
        modname: pick_and_place
        git_dependencies: |
          https://github.com/mt-mods/wield_events
